# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-14 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsup', '0002_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='this is a test description!'),
            preserve_default=False,
        ),
    ]
