# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-17 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsup', '0006_auto_20190917_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
