# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsup', '0007_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
