# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsup', '0010_order_promo_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
