# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-21 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfsup', '0012_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='surfsup.User'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
